-- 1. Selecciona todos los datos de los empleados y los departamentos relacionados
-- 2. Obten el nombre del empleado y el nombre del departamento en el que trabaja
-- 3. Obten el nombre de los empleados y el salario y el nombre del departamento de aquellos empleados cuyo salario es mayor a 2000
-- 3. Obten el nombre de los empleados y el salario y el nombre del departamento de aquellos empleados cuyo salario es mayor a 2000 y que trabajan en el departamento que está en DALLAS
-- 4. Obten los empleados que cobran más que sus jefes
-- 5. Obten los empleados que cobran más que sus jefes (incluyendo comisiones). Son los mismos
-- 6. Obtén el número de empleados que hay en la empresa sin tener en cuenta los que están en DALLAS
-- 7. Obtén el número de empleados de cada departamento, así como el nombre del departamento.
